spring.application.name=book-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/book_management
spring.datasource.username=book_user
spring.datasource.password=book_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true

spring.jooq.sql-dialect=postgres

server.port=8080